/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=typegen.env --include-runtime=false` (hash: df06e4e8cdf7d290685890137a60f732)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	API: Fetcher /* certbot-serverless-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
