export const syncIntervals = ["15m", "1h", "6h", "12h", "1d"] as const;

export type SyncInterval = (typeof syncIntervals)[number];

export interface SystemdUnitOptions {
  certificateName: string;
  deploymentUrl: string;
  destinationDirectory: string;
  interval: SyncInterval;
  unitName: string;
}

export interface RenderedSystemdUnits {
  serviceFileName: string;
  service: string;
  timerFileName: string;
  timer: string;
  installCommand: string;
}

const UNIT_NAME_PATTERN = /^[a-z0-9][a-z0-9_.-]{0,63}$/;
const CONTROL_CHARACTER_PATTERN = /[\u0000-\u001f\u007f]/;

export function suggestedUnitName(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_.-]+/g, "-")
    .replace(/^[^a-z0-9]+|[^a-z0-9]+$/g, "")
    .slice(0, 64);
  return normalized || "certificate";
}

function quoteUnitArgument(value: string): string {
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\$/g, () => "$$")
    .replace(/%/g, "%%")}"`;
}

function normalizeDestination(value: string): string {
  const destination = value.trim().replace(/\/+$/, "");
  if (
    !destination.startsWith("/")
    || destination === ""
    || destination === "/"
    || CONTROL_CHARACTER_PATTERN.test(destination)
    || destination.split("/").includes("..")
  ) {
    throw new Error("Destination must be an absolute directory without parent traversal");
  }
  return destination;
}

function validateDeploymentUrl(value: string): string {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    throw new Error("Deployment URL is invalid");
  }
  if (url.protocol !== "https:" && !(url.protocol === "http:" && ["localhost", "127.0.0.1"].includes(url.hostname))) {
    throw new Error("Deployment URL must use HTTPS");
  }
  return url.toString();
}

function quoteShellArgument(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

export function renderSystemdUnits(options: SystemdUnitOptions): RenderedSystemdUnits {
  const unitName = options.unitName.trim();
  if (!UNIT_NAME_PATTERN.test(unitName)) {
    throw new Error("Unit name must use lowercase letters, numbers, dots, underscores, or hyphens");
  }
  if (!syncIntervals.includes(options.interval)) {
    throw new Error("Unsupported synchronization interval");
  }

  const destination = normalizeDestination(options.destinationDirectory);
  const deploymentUrl = validateDeploymentUrl(options.deploymentUrl);
  const description = (options.certificateName.replace(/[\r\n\\]+/g, " ").trim() || unitName).replace(/%/g, "%%");
  const serviceBase = `certbot-sync-${unitName}`;
  const runtimeDirectory = serviceBase;
  const runtimePath = `/run/${runtimeDirectory}`;
  const extractedPath = `${runtimePath}/bundle`;
  const serviceFileName = `${serviceBase}.service`;
  const timerFileName = `${serviceBase}.timer`;

  const service = `# Contains a scoped certificate deployment URL. Install this file with mode 0600.
# Generated by Certbot Serverless. Do not share it.

[Unit]
Description=Synchronize certificate files for ${description}
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
UMask=0077
RuntimeDirectory=${runtimeDirectory}
RuntimeDirectoryMode=0700
TimeoutStartSec=2min
ExecStart=/usr/bin/curl --fail --silent --show-error --location --output ${quoteUnitArgument(`${runtimePath}/bundle.zip`)} ${quoteUnitArgument(deploymentUrl)}
ExecStart=/usr/bin/unzip -q -o ${quoteUnitArgument(`${runtimePath}/bundle.zip`)} -d ${quoteUnitArgument(extractedPath)}
ExecStart=/usr/bin/install -d -m 0750 ${quoteUnitArgument(destination)}
ExecStart=/usr/bin/install -m 0644 ${quoteUnitArgument(`${extractedPath}/cert.pem`)} ${quoteUnitArgument(`${destination}/cert.pem`)}
ExecStart=/usr/bin/install -m 0644 ${quoteUnitArgument(`${extractedPath}/chain.pem`)} ${quoteUnitArgument(`${destination}/chain.pem`)}
ExecStart=/usr/bin/install -m 0644 ${quoteUnitArgument(`${extractedPath}/fullchain.pem`)} ${quoteUnitArgument(`${destination}/fullchain.pem`)}
ExecStart=/usr/bin/install -m 0600 ${quoteUnitArgument(`${extractedPath}/privkey.pem`)} ${quoteUnitArgument(`${destination}/privkey.pem`)}
ExecStart=/usr/bin/install -m 0644 ${quoteUnitArgument(`${extractedPath}/request.csr`)} ${quoteUnitArgument(`${destination}/request.csr`)}
ExecStart=/usr/bin/install -m 0644 ${quoteUnitArgument(`${extractedPath}/metadata.json`)} ${quoteUnitArgument(`${destination}/metadata.json`)}
`;

  const timer = `[Unit]
Description=Schedule certificate file synchronization for ${description}

[Timer]
OnBootSec=2m
OnUnitActiveSec=${options.interval}
RandomizedDelaySec=1m
AccuracySec=1m
Unit=${serviceFileName}

[Install]
WantedBy=timers.target
`;

  const installerUrl = new URL(deploymentUrl);
  installerUrl.pathname = `${installerUrl.pathname.replace(/\/$/, "")}/install.sh`;
  installerUrl.search = new URLSearchParams({ unitName, destination, interval: options.interval }).toString();
  installerUrl.hash = "";
  const installCommand = `(
  set -eu
  umask 077
  certbot_installer=$(mktemp)
  trap 'rm -f "$certbot_installer"' EXIT
  trap 'exit 1' HUP INT TERM
  curl -fsSL ${quoteShellArgument(installerUrl.toString())} -o "$certbot_installer"
  if [ "$(id -u)" -eq 0 ]; then
    sh "$certbot_installer"
  else
    sudo sh "$certbot_installer"
  fi
)`;

  return { serviceFileName, service, timerFileName, timer, installCommand };
}

export function renderSystemdInstaller(options: SystemdUnitOptions): string {
  const units = renderSystemdUnits(options);
  return `#!/bin/sh
set -eu

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this installer as root or with sudo." >&2
  exit 1
fi
for certbot_dependency in curl unzip install systemctl; do
  if ! command -v "$certbot_dependency" >/dev/null 2>&1; then
    echo "Missing required command: $certbot_dependency" >&2
    exit 1
  fi
done
if ! systemctl show-environment >/dev/null 2>&1; then
  echo "This installer requires a Linux host running systemd." >&2
  exit 1
fi

umask 077
certbot_unit_dir=$(mktemp -d)
trap 'rm -rf "$certbot_unit_dir"' EXIT
trap 'exit 1' HUP INT TERM

cat > "$certbot_unit_dir/${units.serviceFileName}" <<'CERTBOT_SERVICE_EOF'
${units.service}CERTBOT_SERVICE_EOF
cat > "$certbot_unit_dir/${units.timerFileName}" <<'CERTBOT_TIMER_EOF'
${units.timer}CERTBOT_TIMER_EOF

install -d -m 0755 /etc/systemd/system
install -m 0600 "$certbot_unit_dir/${units.serviceFileName}" /etc/systemd/system/${units.serviceFileName}
install -m 0644 "$certbot_unit_dir/${units.timerFileName}" /etc/systemd/system/${units.timerFileName}
systemctl daemon-reload
systemctl enable ${units.timerFileName}
systemctl restart ${units.timerFileName}
systemctl start ${units.serviceFileName}
echo "Installed ${units.serviceFileName} and ${units.timerFileName}; certificate files synchronized."
`;
}
